version: "3"
services:
  datascience-notebook:
    image: jupyter/datascience-notebook
    volumes:
      - ./data:/home
    user: root
    environment:
      - NB_USER=jupyternb
      - NB_UID=1000
      - NB_GID=100
      - CHOWN_HOME=yes
    ports:
      - 8888:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    container_name: datascience-notebook-container
